[package]
name = "advent-of-code-2020"
version = "0.1.0"
authors = ["Yoeri Otten <yoeori@live.nl>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
lazy_static = "1.4.0"
ansi_term = "0.12"
